name: 🐛 缺陷反馈
description: 请填写表单，方便我们快速定位 Android 端问题。
title: "[Bug] 一句话描述问题"
labels: ["bug"]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      placeholder: |
        1. 打开 App → 点击 XX 按钮
        2. 打开 设置 → 点击 XX 按钮
        3. 崩溃 / 白屏 / 无响应
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际结果
      description: 可贴截图或录屏。
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 预期结果
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App 版本
      placeholder: 例：v1.2.3（在设置→关于里查看）
    validations:
      required: true

  - type: dropdown
    id: abi
    attributes:
      label: CPU 架构 / ABI
      options:
        - arm64-v8a
        - armeabi-v7a
        - x86_64
        - 不清楚
    validations:
      required: true

  - type: dropdown
    id: android
    attributes:
      label: Android 系统版本
      options:
        - 14
        - 13
        - 12
        - 11
        - 10
        - 9 及以下
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: 手机型号
      placeholder: 例：Xiaomi 13 / Samsung S23
    validations:
      required: true

  - type: textarea
    id: logcat
    attributes:
      label: 相关日志（logcat）
      description: 请用 `adb logcat | grep <包名>` 截取崩溃前后 50 行，或上传 txt 文件。
      render: shell